### PR TITLE
Create runtime.txt

### PR DESCRIPTION
**Pull request by alanlujan91**
Mybinder should be python>=3.8

### CODE REVIEW

**Comment by alanlujan91** [comment]
From mybinder documentation https://mybinder.readthedocs.io/en/latest/howto/languages.html

**Comment by alanlujan91** [comment]
@camriddell we had to do this because mybinder.org (online) was not running some notebooks because the default python is 3.7, which is not compatible with HARK-dev. 

It may be necessary to do this for some of the REMARK's as well.

**Comment by alanlujan91** [comment]
Actually, another point is that maybe the website should not point at DEMARK-dev, but at DEMARK-last-release. In the readme, you can pick between launching the (dev branch) or the (stable release). The stable release seems to work, since it's pinned to econ-ark=0.12.0. But then the website in https://econ-ark.org/materials/tractablebufferstock-interactive points to the DEMARK/HEAD, where maybe it should point to DEMARK/0.12.

**Comment by llorracc** [comment]
Yes.  I think it was @sbenthall who proposed a while ago that DemARKs should have versioning that matches the HARK versions.  But we've not implemented that -- the current DemARK repo is on version 0.11.  I think somewhere there's a checklist for things we need to do when there's a new release -- updating the DemARK release version should be added to that list.

**Comment by llorracc** [comment]
@sbenthall, you probably know where the checklist is?

**Pull request merged**
