### PR TITLE
Add a notebook on how IndShockConsumerType is solved.

### PR DESCRIPTION
**Pull request by pkofod**
@mgerring would love your input on this. This comes from a person who's read the code and written down the steps, but you may have some important/interesting things to add. 

The title says "how" but it's *not* a math notebook, it's a notebook on how the actual program is *organized*.

### CODE REVIEW

**Comment by pkofod** [comment]
Oops, tagged the wrong matt @mnwhite

**Comment by mnwhite** [comment]
In addition to Karsten looking at this (it was written somewhat with him in mind), I've shared this with my colleague Jorge Soares.

**Comment by llorracc** [comment]
This needs to be merged with the one that Karsten made.

**Comment by pkofod** [comment]
Is that this one? https://github.com/econ-ark/DemARK/blob/b009a0922a540559274e4e5718de27a5b3d8c6fb/notebooks/Quickstart_tutorial/Quick_start_with_solution.ipynb

**Comment by llorracc** [comment]
@sbenthall is working on a "how to get started with HARK" project that this is part of

**Comment by sbenthall** [comment]
My next steps:
1) Review the notebook in this PR, merge if good
2) Look at the Quickstart notebook and see if this can be combined with it
3) Move both of these into HARK/examples/ after https://github.com/econ-ark/HARK/pull/442 is merged as part of https://github.com/econ-ark/HARK/issues/459

**Comment by sbenthall** [comment]
Notebook looks very good to me. Next steps now in issue #81 . Merging.

**Pull request merged**
