### PR TITLE
Fixed dead links in ConsIndShock notebook using Jupytext

### PR DESCRIPTION
**Pull request by ccutsail**
I was trying to work with the ConsIndShock model here: https://econ-ark.org/notebooks/ and found that the link to the REMARK was dead, so I updated it. I checked the other links in the notebook, and the link to the HARK documentation was also dead so I updated that one too. It doesn't seem to be a browser-specific thing, as I tried the both sets of links in Chrome, Safari, and FireFox as well as on my phone and the dead ones are dead everywhere and the updated ones work everywhere.

### CODE REVIEW

**Comment by mnwhite** [comment]
Thanks, I think this is due to a change in GitHub's URL structure.  This
problem might crop up other places as well.

Can you revert the -checkpoint file (we really need to gitignore these)?

**Comment by llorracc** [comment]
@ccutsail Thanks!  
@mnwhite .ipynb_checkpoints is in the .gitignore file, and according to [this](https://stackoverflow.com/questions/35916658/how-to-git-ignore-ipython-notebook-checkpoints-anywhere-in-repository) that is supposed to work.  

But when you add something to the .gitignore file, the confusing thing is that anything that was _previously_ being tracked still hangs around and continues being tracked.  The file should be named something like .gitignore_newfiles or something to avoid confusion.

I've just gone in and deleted (and stopped tracking) the old versions of these files, so now they are gone from the master repo.  I'm guessing that Cory downloaded DemARK before we added .ipynb_checkpoints to the .gitignore file so that's why it wasn't being ignored for him.  

Cory, if you revert or delete the .checkpoint file and update the PR, I *think* it will remove the conflict...

PS.  I think you meant the link to the DemARK; there's no REMARK for ConsIndShockModel.py.

**Comment by ccutsail** [comment]
I deleted the -checkpoint file from my master.

It was actually the link to the REMARK for SolvingMicroDSOPs, not ConsIndShock. Toward the bottom of the notebook. 

I think this is good now, right?

**Comment by llorracc** [comment]
@ccutsail Thanks for updating.  

PS.  Actually, looking at your changes, I think the old dead links maybe never worked, I probably typed them in by hand without checking them, having (incorrectly) thought that I understood the pattern for constructing GitHub urls.   Merging now.

**Pull request merged**
