### PR TITLE
Fixes to DemARKs to remove dependence on ConsumerParamaters

### PR DESCRIPTION
**Pull request by sbenthall**
Addresses #81 and #109

Only failing DemARK currently for this PR is Chinese Growth.
It is failing because of the issue raised in #109.

Fixing this will require a change to HARK's `constructLognormalIncomeProcessUnemployment` function

### CODE REVIEW

**Comment by sbenthall** [comment]
This PR is now ready to merge and fixes the dependencies on ConsumerParameters

**Comment by llorracc** [comment]
@sbenthall, @MridulS : This seems like perfect first application of the workflow we have discussed elsewhere: We should put the Chinese Growth notebook on a "HARK-commit-#####-breaks-this" branch of DemARK, and worry about fixing it later.

@MridulS, can you execute on this?  Merge @sbenthall's PR, then make that branch on DemARK and move Chinese Growth to it?  Then as far as I'm concerned we will be ready to make the release and post the blog post.

**Comment by sbenthall** [comment]
@llorracc I've since fixed Chinese Growth in this PR (today)
So it is unnecessary for @MridulS to make the extra branch.

This PR can just be merged, in my view.

**Comment by MridulS** [comment]
notebooks/PerfForesightCRRA-Approximation.py isn't updated?

**Comment by sbenthall** [comment]
Good catch. Thank you. I've pushed a commit to fix.

**Pull request merged**
