### PR TITLE
DCEGM DemARK.

### PR DESCRIPTION
**Pull request by pkofod**
This can be merged after https://github.com/econ-ark/HARK/pull/226 is merged, and the first cell is adjusted to `import` instead of just redefining the functions here. cc @llorracc 

The point of this little DemARK is basically to show to to use part of the DCEGM functionality. A RemARK/REMARK(?) will follow with an actual model being solved using these and other tools.

### CODE REVIEW

**Comment by mnwhite** [comment]
Awesome, thank you.

**Comment by pkofod** [comment]
The Jupytext stuff seems to work this time @llorracc, but again.. this is done from my laptop which is the computer where it always worked. I must have borked my Jupytext installation on my desktop somehow.

**Comment by pkofod** [comment]
Alright, I made some changes, but it's not quite there yet, because I'm still waiting for the Zotero log-in, and I can't for the life of me get the "codefolding" extension to work (doing what the manual link below tells me to does not do it for me). I must try another system, or try to wipe my install as I've had so many problems with jupyter extensions here (jupytext, codefolding, ...)
https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/codefolding/readme.html

When the REMARK is merged, I can refer directly to it. As I update the REMARK, I'll also update the values in the example here.

**Comment by llorracc** [comment]
PR associated with dev release of DCEGM tools

**Comment by llorracc** [comment]
Release Notes: Explains and explores the [dcegm.py](https://github.com/econ-ark/HARK/blob/master/HARK/dcegm.py) module's tools for solving Discrete-Continuous problems.

**Pull request merged**
