### PR TITLE
Turn YMCankus's notebook into a paired jupytext notebook

### PR DESCRIPTION
**Pull request by pkofod**
See https://github.com/econ-ark/DemARK/pull/9

I kept @YMCankus 's commit, so he'll get credit for his work as he should! #9 can be closed, and this should be merged instead (if everyone agrees on the content).

Sorry to keep you waiting for so long @YMCankus, a PR can quickly vanish in the pile of stuff to be done :)

### CODE REVIEW

**Comment by YMCankus** [comment]
I'm in the same situation, after taking care of my other tasks, I will try to allocate time on this project for its other issues.

**Comment by pkofod** [comment]
bump @llorracc

**Comment by mnwhite** [comment]
Actually bump for me, I think.

**Comment by pkofod** [comment]
oh, okay. Bump @mnwhite ;)

**Pull request merged**
